### ISSUE TITLE
OntologyTerm should be OntologyClass

### ISSUE THREAD

**Issue by julesjacobsen** [ga4gh-schemablocks/blocks#11]
In Phenopackets, we don't use OntologyTerm, we use OntologyClass

https://github.com/phenopackets/phenopacket-schema/blob/48839671d421bff3ab08b90925713124daeb60db/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L70-L81

https://phenopackets-schema.readthedocs.io/en/latest/ontologyclass.html

**Comment by mbaudis** [comment]
@julesjacobsen In the spirit of alignment & in the current "test phase" w/o AFAIK dependencies I'd favour to change to `OntologyClass`. @mcourtot?

**Comment by mbaudis** [comment]
Closing this since accepted change implemented in the JSON Schem re-write https://github.com/ga4gh-schemablocks/blocks-json-schema/blob/master/src/yaml/OntologyClass.yaml .
