### ISSUE TITLE
Schema provenance, authorship, use cases...

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-schemablocks/blocks#3]
I propose to add some attributes to indicate the provenance & use of the documented schemas. We already have `status` (currently "proposed" by default - need separate issue to document values there & their meaning); but more provenance documentation is needed. First ideas:

* `authors`
    - array
    - well, the names of people who have a decisive role in shaping the schema block
* `use_cases`
    - array of strings or objects
    - where this schema has been implemented, with description, link (therefore more structure w/ `url` attribute etc?)

The `authors` attribute will already be parsed into the web representation by the current `yaml2json.pl` tool.

**Comment by mbaudis** [comment]
We have implemented this now in the current representation for some of the blocks; please have a look + comment.

**Comment by Relequestual** [comment]
Sorry, I don't feel I can review any schemas till there's a documented governance process in place.

**Comment by mbaudis** [comment]
Issue moved to a new general discussion of structured page elements for standards for SchemaBlocks https://github.com/ga4gh-schemablocks/ga4gh-schemablocks.github.io/issues/8
