### ISSUE TITLE
Data Use should be Ontology_class Array

### ISSUE THREAD

**Issue by aaliomer** [ga4gh-schemablocks/blocks#4]
In DUO, you are able to add secondary and primary use cases.
Also, you might want to add two or more data use cases (cancer and diabetes research for example)

If a biosample can have one data use code, should a biosample have more than one schemablock? that's a data management headache. having a set of data use codes instead of one might solve it

**Comment by mbaudis** [comment]
That's a good point. In principle, we could use the general way this is dome e.g. for `external_references` and `biocharacteristics`; having an array of `data_use_conditions`, where each consists of a reference-object (like) object:

```
"data_use_conditions":
  [
    {
      "description" : "study derived data use",
      "type": {
        "id": "DUO_0000003",
        "label": "genetic studies only"
      },
    },
    {
      "description" : "institutional data use policy",
      "type": {
        "id": "DUO:0000004",
        "label": "no restrictions"
      },
    },
  ]
```
Not sure if this is a good example; happy about others. 

But generally, I like the structure of those list objects, where one always can address a specific identifier through `my_attribute_name.type.id` (or in Perl etc. `$attributes->{my_attribute_name}->{type}->{id}`). 

Maybe @mcourtot can comment?

**Comment by aaliomer** [comment]
i think this is a good idea. in my humble opinion, we can keep the flat nature of the data use condition object by getting rid of the type and keep the properties: description, type and label. 
the reason is that the id is prefixed with the ontology source (I.E DUO:XXXX)
I think this is good enough. otherwise we can add a type field. 
remember all of that is to keep the flat nature of this schema :)

**Comment by mcourtot** [comment]
Just saw this :) 
See also https://github.com/ga4gh-schemablocks/blocks/issues/5

**Comment by mbaudis** [comment]
Closing this since it is discussed _in extenso_ in https://github.com/ga4gh-schemablocks/blocks/issues/5. Will rename the topic there, though.
