### ISSUE TITLE
Add type information to ID references

### ISSUE THREAD

**Issue by cmungall** [ga4gh-schemablocks/blocks#9]
My reading of the intent is that SB aims to be modular, with limited inlining/nesting, and for entities to be linked via IDs (foreign to primary in SQL terms).

If so it would be useful to have a typing mechanism to make it clear how objects should be interconnected.

E.g.
https://schemablocks.org/schemas/blocks/Individual.html
Has an array of biocharacteristics - what type are these?

**Comment by mbaudis** [comment]
@cmungall Good point; that information is in the YAML source, but not translated to the webpage (It is in the description, but not as the attribute).

We'll work on the tooling together with the JSON Schema redesign of the blocks format (@Relequestual ...).

```
      biocharacteristics:
        description: |
          list of Phenotype objects with properly prefixed term ids, describing features of the individual which are not specific to the reported biosample(s); typical examples here are sex, species and "systemic" phenotypes and diseases
        type: array
        items:
          ref: './Phenotype'
        example:
          - description: 'Patient with Down syndrome'
            type :
              id : 'HP:0003745'
              label : 'Genetic anticipation'
        queries:
          - query: 'db.individual.find( { "biocharacteristics.type.id" : "NCBITaxon:9606" } )'
            description: the query will return all individuals who have been properly labeled as human
          - query: 'db.biosamples.distinct( { "biocharacteristics.type.id", "biocharacteristics.type.id" : { $regex : /HP\:/i } } )'
            description: this call to the distinct funcion will return *all* HPO annotated classes
```

**Comment by mbaudis** [comment]
@cmungall @Relequestual The type indication on the web pages has been fixed for now (see e.g. your [example](https://schemablocks.org/schemas/blocks/Individual.html)). This is a temporary solution until we have the clean JSON Schema version.
